### ISSUE TITLE
🐞[Bug] Error forbidden upload version

### ISSUE THREAD

**Issue by FuriosoJack** [DavidAnderson684/simba-plugin-manager-updater#18]
Hello,

When a .zip of a version is going to be uploaded, an error is presented in the http request that is generated when the page is loaded.

![image](https://user-images.githubusercontent.com/26976637/197834697-55873aab-a2fb-46ec-af15-c0c9a6d0e3c2.png)

Apparently this causes that when clicking on the input file of the file, the native browser window does not appear to load the file.

![image](https://user-images.githubusercontent.com/26976637/197834981-166e67f7-7e3d-45d3-b9cf-01e83db91fb7.png)

**Comment by DavidAnderson684** [comment]
The 403 error in the console is desired and expected. The browser is checking that the directory where the plugins are stored does not allow directory listing.
