### ISSUE TITLE
[feature] PSR-4 for class

### ISSUE THREAD

**Issue by FuriosoJack** [DavidAnderson684/simba-plugin-manager-updater#19]
Hello bro, greetings could you add that your class has psr-4 I am adding unit tests to my plugins and I would like to be able to use your plugin better.

Thank you

**Comment by DavidAnderson684** [comment]
If you want to send in a patch, I am happy to review it for inclusion.

**Comment by FuriosoJack** [comment]
Great, I'll code a bit when I have some time. By the way, david do you know if in the Simba Plugin Updates Manager plugin, how can I make it so that different users can see the plugins of an administrator or a specific user?

**Comment by DavidAnderson684** [comment]
Is that the same question that I answered here?

https://wordpress.org/support/topic/access-the-same-plugin-package-from-different-users/

**Comment by FuriosoJack** [comment]
Ahh si si David, gracias. Sabes si esto se deba al debug del wordpress o a una configuracion del plugin, no me gustaria que apareciera

![image](https://user-images.githubusercontent.com/26976637/208251394-4c976bd2-69d5-4be2-bcc3-7b2c3745113e.png)
