### ISSUE TITLE
Error in minor versions due to updating Updraft_Manager_Updater_1_8

### ISSUE THREAD

**Issue by FuriosoJack** [DavidAnderson684/simba-plugin-manager-updater#24]
I considered that the version 1.9 in PR https://github.com/DavidAnderson684/simba-plugin-manager-updater/pull/23 that was released should be renamed to a **major** version since it implies a change in my code from Updraft_Manager_Updater_1_8 to Updraft_Manager_Updater_1_9 and **the semantic version is not preserved.**
_My current composer.json dependence_
`  "require": {    
    "davidanderson684/simba-plugin-manager-updater": "^1.8"
  },`

The correct tag version of this update should be v2.0.0

Since other developers who use Simba as a dependency will have errors in their plugins, in my case I launched an update to my clients and their WordPress automatically received a failed error.

![image](https://github.com/DavidAnderson684/simba-plugin-manager-updater/assets/26976637/2899ad67-8422-45a0-8615-99f36264ae18)

**Comment by DavidAnderson684** [comment]
The fact that the version number is included in the class name makes it clear that this project is not currently (and never has been) using semantic versioning. 
As per the changelog, read `UPGRADING.md` for update instructions, and as per `README.md`, use rules like `davidanderson684/simba-plugin-manager-updater": "1.8.*"` in your `composer.json`.
