### ISSUE TITLE
Custom icons

### ISSUE THREAD

**Issue by htmgarcia** [DavidAnderson684/simba-plugin-manager-updater#25]
Is there a way to define custom icon URLs in the updates page for plugins?

![Screenshot 2024-01-25 at 11 13 23 a m](https://github.com/DavidAnderson684/simba-plugin-manager-updater/assets/4999794/e6991ad7-5200-466d-98de-d3f7b4ab5669)

**Comment by DavidAnderson684** [comment]
Hi,
Not currently, but feel free to send a patch! https://github.com/YahnisElsts/plugin-update-checker/issues/431 indicates that it's just a matter of including an entry in the returned JSON.
David
