### ISSUE TITLE
udmupdater_entercustomerlogin filter in use 3 times

### ISSUE THREAD

**Issue by htmgarcia** [DavidAnderson684/simba-plugin-manager-updater#26]
`udmupdater_entercustomerlogin` filter is in use in 3 places with variable params. Maybe the solution is to rename each one to make them unique?

https://github.com/DavidAnderson684/simba-plugin-manager-updater/blob/master/class-udm-updater.php#L723
https://github.com/DavidAnderson684/simba-plugin-manager-updater/blob/master/class-udm-updater.php#L731
https://github.com/DavidAnderson684/simba-plugin-manager-updater/blob/master/class-udm-updater.php#L744

**Comment by DavidAnderson684** [comment]
Apologies - two of those are just copy/paste errors (i.e. I omitted to change the filter name). I've fixed that now in https://github.com/DavidAnderson684/simba-plugin-manager-updater/releases/tag/v1.9.2
